### ISSUE TITLE
Could not restore subscribers

### ISSUE THREAD

**Issue by rozatoo** [ramteid/EbayKleinanzeigenCrawler#1]
Hi, Beginner coder here, 
I cloned this project and executed it with Visual Studio, when I do this it tells me that I'm missing the file Subscribers.json. 
Do I need to add this file manually? How exactly do I go about adding new Items I want to watch?

**Comment by ramteid** [comment]
At first run, you can ignore the error message because the Subscribers.json is just not created yet. It will be created automatically once you add subscriptions.
First you'll need to create a Telegram bot (google "How to create Telegram bot") and copy the bot's token into the right place in TelegramManager.cs. Then run the project and send your bot a message on Telegram (/help).

**Comment by rozatoo** [comment]
After creating a second Telegram bot I got it to work, thanks! Works great!
